# Configuration for pre-commit hooks, see: https://pre-commit.com/
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        # 1 MB - Don't commit notebooks with output!
      - id: trailing-whitespace
      - id: check-yaml
        exclude: "^src/pydantic_yaml/examples/base_models/recursive.yaml$"
      - id: check-toml
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.15.18"
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ^(tests).*$
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    # NOTE: This passes ALL files to `mypy`. mypy will cache these.
    # However, we must ignore all missing imports, because pre-commit runs in a separate env
    rev: "v2.1.0"
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          [
            --config-file,
            pyproject.toml,
            --ignore-missing-imports,
            --install-types,
            --non-interactive,
          ]

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 1.1.1 # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    hooks:
      - id: pyrefly-check
        pass_filenames: false # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
        language: system # Use system-installed pyrefly
        entry: uv run pyrefly check .

  - repo: https://github.com/astral-sh/ty-pre-commit
    # ty version.
    rev: v0.0.51
    hooks:
      - id: ty

  # SEE: https://pre-commit.com/#repository-local-hooks
  # - repo: local
  #   hooks:
  #     - id: foo
  #       name: foo
  #       entry: foo
  #       language: system
  #       description: "Example local hook, see https://pre-commit.com/#repository-local-hooks"
