# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: "ubuntu-24.04"
  tools:
    # We are using "pip" to install
    python: "mambaforge-22.9"

conda:
  environment: environment.yml
