name: "CI v2 Dev Workflow"

on:
  push:
    branches:
      - v2-dev
  pull_request:
    branches:
      - v2-dev
env:
  RELEASE_PYTHON_VERSION: "3.10"

jobs:
  ci-matrix:
    name: "CI Matrix"
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
        deps:
          - dev,docs
        lib-pydantic:
          - "2.9"
    uses: ./.github/workflows/ci-single.yml
    with:
      python-version: ${{ matrix.python-version }}
      pydantic-install: >
        "pydantic~=${{ matrix.lib-pydantic }}"
      lib-install: >
        -e ".[${{ matrix.deps }}]"
    secrets: inherit
