# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: "Unit Tests"
    uses: ./.github/workflows/test-matrix.yml
    with:
      python-versions: '["3.10", "3.14"]'
      dep-groups: '["--only-dev", "--all-groups"]'
      pydantic-versions: '["1.10.22", "2.12.5"]'
      ruamel-versions: '["NOTSET", "0.17.40", "0.18.11", "0.19.1"]'
      exclude-matrix: '[{"python-version": "3.14", "lib-pydantic": "1.10.22"}]'
      fail-fast: false
