# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: "Unit Tests"
    uses: ./.github/workflows/test-matrix.yml
    with:
      python-versions: '["3.10", "3.14"]'
      dependency-resolution: '["highest"]'
      dep-groups: '["--only-dev", "--all-groups"]'
      fail-fast: false
