# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
# Updated to use uv, as per docs here:
# https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi
# https://github.com/astral-sh/trusted-publishing-examples/blob/main/.github/workflows/release.yml

name: Build & Upload package

on:
  release:
    types: [created]

env:
  gha-uv-version: "0.11.5"
  gha-python-version: "3.10"

jobs:
  ci-check:
    name: "Pre-publishing CI Checks"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true # we want CI to immediately fail for releases
      matrix:
        python-version:
          - "3.10"
          - "3.13"
        dep-groups:
          - "--only-dev"
          - "--all-groups"
        lib-pydantic:
          - "1.10.22" # last supported versions of Pydantic v1
          # - "2.5.0" # first version to support python 3.12 - we are testing 3.13 now
          - "2.12.5"
        lib-ruamel:
          - "NOTSET"
          - "0.17.40"
          - "0.18.11"
    steps:
      - uses: actions/checkout@v6

      - name: "Install uv and python ${{ matrix.python-version }}"
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: ${{ env.gha-uv-version }}

      - name: Install package and dependencies according to matrix
        run: |
          uv sync ${{ matrix.dep-groups }}
          if [ ${{ matrix.lib-ruamel }} != "NOTSET" ]
          then
            uv add "ruamel.yaml~=${{ matrix.lib-ruamel }}"
          fi
          uv add "pydantic~=${{ matrix.lib-pydantic }}"

      - name: Lint with ruff
        run: |
          uv run ruff check .
      - name: Test with pytest
        run: |
          uv run pytest
      - name: Test with mypy
        run: |
          uv run mypy -p pydantic_yaml

  publish-pypi:
    name: "Publish to PyPI"
    needs:
      - "ci-check"
    runs-on: ubuntu-latest
    environment:
      name: "publish-pypi"
    permissions:
      id-token: write # required for trusted publishing
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.gha-uv-version }}
      - name: "Install Python"
        run: uv python install ${{ env.gha-python-version }}
      - name: Build
        run: uv build

      # Check that basic features work and we didn't miss to include crucial files
      # - name: Smoke test (wheel)
      #   run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      # - name: Smoke test (source distribution)
      #   run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py

      - name: Publish package distributions to PyPI
        run: uv publish
